fix: ipvanish zip location
qdm12/gluetun pull request #1449
Opened 2023-03-10 19:16 UTC by stevenl4

Updated the url to get the zip file for ipvanish

2023-03-24 12:05 UTC, qdm12 approved these changes
Thanks 💯

2023-03-25 07:09 UTC, qdm12 requested changes
Can you fix the related tests (see https://github.com/qdm12/gluetun/actions/runs/4510969730/jobs/7942558428?pr=1449)? I think just batch replacing the old string from the entire codebase would do 😉 Thanks

2023-03-25 12:44 UTC, stevenl4 reviewed
updated tests with same url

2023-03-25 14:36 UTC, qdm12 approved these changes

2023-03-25 14:36 UTC, merged